name: Deploy to GitHub Pages 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --mode production

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3 # Upload build artifacts for GitHub Pages
        with:
           name: 'github-pages' # Name of the artifact
           path: dist # Path to the build output directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4 # Deploy the artifacts to GitHub Pages
        with: 
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
          artifact_name: 'github-pages' # Name of the artifact to deploy